# Welcome to Jekyll!
#

# Site settings
title: Desimslaughter
description: |
  Home of Desi M. Slaughter,
  an Influencer, Designer and
  Creativepreneur in Houston, TX
owner: Desi M. Slaughter # or company name
first_published: 2012 # if migrating another site, the year of your first publish
email: desi@desimslaughter.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://desimslaughter.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/desimslaughter
  github: https://github.com/desimslaughter
  linkedin-square: https://linkedin.com/in/desireemslaughter
  facebook-official: https://facebook.com/desimslaughter
  google-plus-square: https://plus.google.com/u/0/+DesireeDesiSlaughter
  instagram: https://instagram.com/desimslaughter
  #email: /contact/
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
